apiVersion: jalapeno.srv6/v1
kind: PathRequest
metadata:
  name: path-request
spec:
  defaultVrf:
    ipv6:
      routes:
        - name: example
          graph: radix_8_graph
          path_type: best-paths
          limit: 3
          source: radix_8_node/10.0.0.4_4200000004
          destination: radix_8_node/10.0.0.35_4200000035
          direction: outbound