hostname sw005
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.5
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1005::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65005
 bgp router-id 1.1.0.5
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:17:: remote-as 65004
 neighbor 2001:db8:1:17:: capability extended-nexthop
 neighbor 2001:db8:1:1f::1 remote-as 65009
 neighbor 2001:db8:1:1f::1 capability extended-nexthop
 neighbor 2001:db8:1:20::1 remote-as 65018
 neighbor 2001:db8:1:20::1 capability extended-nexthop
 neighbor 2001:db8:1:21::1 remote-as 65027
 neighbor 2001:db8:1:21::1 capability extended-nexthop
 neighbor 2001:db8:1:22::1 remote-as 65036
 neighbor 2001:db8:1:22::1 capability extended-nexthop
 neighbor 2001:db8:1:23::1 remote-as 65038
 neighbor 2001:db8:1:23::1 capability extended-nexthop
 neighbor 2001:db8:1:24::1 remote-as 65047
 neighbor 2001:db8:1:24::1 capability extended-nexthop
 neighbor 2001:db8:1:25::1 remote-as 65056
 neighbor 2001:db8:1:25::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1005::/48
  network fc00:0:1005::1/128
  neighbor 2001:db8:1:17:: activate
  neighbor 2001:db8:1:17:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:1f::1 activate
  neighbor 2001:db8:1:1f::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:20::1 activate
  neighbor 2001:db8:1:20::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:21::1 activate
  neighbor 2001:db8:1:21::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:22::1 activate
  neighbor 2001:db8:1:22::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:23::1 activate
  neighbor 2001:db8:1:23::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:24::1 activate
  neighbor 2001:db8:1:24::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:25::1 activate
  neighbor 2001:db8:1:25::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1005::/48 locator MAIN behavior uN
   sid fc00:0:1005:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:17::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:1f::1
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet8 nexthop 2001:db8:1:20::1
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet12 nexthop 2001:db8:1:21::1
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet16 nexthop 2001:db8:1:22::1
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet20 nexthop 2001:db8:1:23::1
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet24 nexthop 2001:db8:1:24::1
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet28 nexthop 2001:db8:1:25::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1005::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1005::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
