hostname sw045
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.45
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:102d::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65045
 bgp router-id 1.1.0.45
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:1d:: remote-as 65004
 neighbor 2001:db8:1:1d:: capability extended-nexthop
 neighbor 2001:db8:1:61:: remote-as 65015
 neighbor 2001:db8:1:61:: capability extended-nexthop
 neighbor 2001:db8:1:6e:: remote-as 65017
 neighbor 2001:db8:1:6e:: capability extended-nexthop
 neighbor 2001:db8:1:9d:: remote-as 65026
 neighbor 2001:db8:1:9d:: capability extended-nexthop
 neighbor 2001:db8:1:bb:: remote-as 65035
 neighbor 2001:db8:1:bb:: capability extended-nexthop
 neighbor 2001:db8:1:c1:: remote-as 65037
 neighbor 2001:db8:1:c1:: capability extended-nexthop
 neighbor 2001:db8:1:d5::1 remote-as 65046
 neighbor 2001:db8:1:d5::1 capability extended-nexthop
 neighbor 2001:db8:1:d6::1 remote-as 65055
 neighbor 2001:db8:1:d6::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:102d::/48
  network fc00:0:102d::1/128
  neighbor 2001:db8:1:1d:: activate
  neighbor 2001:db8:1:1d:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:61:: activate
  neighbor 2001:db8:1:61:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:6e:: activate
  neighbor 2001:db8:1:6e:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:9d:: activate
  neighbor 2001:db8:1:9d:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:bb:: activate
  neighbor 2001:db8:1:bb:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:c1:: activate
  neighbor 2001:db8:1:c1:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:d5::1 activate
  neighbor 2001:db8:1:d5::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:d6::1 activate
  neighbor 2001:db8:1:d6::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:102d::/48 locator MAIN behavior uN
   sid fc00:0:102d:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:1d::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:61::
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet8 nexthop 2001:db8:1:6e::
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet12 nexthop 2001:db8:1:9d::
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet16 nexthop 2001:db8:1:bb::
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet20 nexthop 2001:db8:1:c1::
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet24 nexthop 2001:db8:1:d5::1
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet28 nexthop 2001:db8:1:d6::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:102d::1
  exit
  locators
   locator MAIN
    prefix fc00:0:102d::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
