hostname sw033
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.33
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1021::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65033
 bgp router-id 1.1.0.33
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:38:: remote-as 65008
 neighbor 2001:db8:1:38:: capability extended-nexthop
 neighbor 2001:db8:1:46:: remote-as 65011
 neighbor 2001:db8:1:46:: capability extended-nexthop
 neighbor 2001:db8:1:6c:: remote-as 65017
 neighbor 2001:db8:1:6c:: capability extended-nexthop
 neighbor 2001:db8:1:8e:: remote-as 65023
 neighbor 2001:db8:1:8e:: capability extended-nexthop
 neighbor 2001:db8:1:b3::1 remote-as 65036
 neighbor 2001:db8:1:b3::1 capability extended-nexthop
 neighbor 2001:db8:1:b4::1 remote-as 65042
 neighbor 2001:db8:1:b4::1 capability extended-nexthop
 neighbor 2001:db8:1:b5::1 remote-as 65048
 neighbor 2001:db8:1:b5::1 capability extended-nexthop
 neighbor 2001:db8:1:b6::1 remote-as 65054
 neighbor 2001:db8:1:b6::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1021::/48
  network fc00:0:1021::1/128
  neighbor 2001:db8:1:38:: activate
  neighbor 2001:db8:1:38:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:46:: activate
  neighbor 2001:db8:1:46:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:6c:: activate
  neighbor 2001:db8:1:6c:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:8e:: activate
  neighbor 2001:db8:1:8e:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:b3::1 activate
  neighbor 2001:db8:1:b3::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:b4::1 activate
  neighbor 2001:db8:1:b4::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:b5::1 activate
  neighbor 2001:db8:1:b5::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:b6::1 activate
  neighbor 2001:db8:1:b6::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1021::/48 locator MAIN behavior uN
   sid fc00:0:1021:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:e000::/48 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:38::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet1 nexthop 2001:db8:1:46::
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet2 nexthop 2001:db8:1:6c::
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet3 nexthop 2001:db8:1:8e::
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:b3::1
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet5 nexthop 2001:db8:1:b4::1
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet6 nexthop 2001:db8:1:b5::1
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet7 nexthop 2001:db8:1:b6::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1021::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1021::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
