hostname sw040
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.40
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1028::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65040
 bgp router-id 1.1.0.40
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:14:: remote-as 65003
 neighbor 2001:db8:1:14:: capability extended-nexthop
 neighbor 2001:db8:1:47:: remote-as 65011
 neighbor 2001:db8:1:47:: capability extended-nexthop
 neighbor 2001:db8:1:79:: remote-as 65019
 neighbor 2001:db8:1:79:: capability extended-nexthop
 neighbor 2001:db8:1:a0:: remote-as 65027
 neighbor 2001:db8:1:a0:: capability extended-nexthop
 neighbor 2001:db8:1:ba:: remote-as 65035
 neighbor 2001:db8:1:ba:: capability extended-nexthop
 neighbor 2001:db8:1:cc::1 remote-as 65043
 neighbor 2001:db8:1:cc::1 capability extended-nexthop
 neighbor 2001:db8:1:cd::1 remote-as 65044
 neighbor 2001:db8:1:cd::1 capability extended-nexthop
 neighbor 2001:db8:1:ce::1 remote-as 65052
 neighbor 2001:db8:1:ce::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1028::/48
  network fc00:0:1028::1/128
  neighbor 2001:db8:1:14:: activate
  neighbor 2001:db8:1:14:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:47:: activate
  neighbor 2001:db8:1:47:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:79:: activate
  neighbor 2001:db8:1:79:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:a0:: activate
  neighbor 2001:db8:1:a0:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:ba:: activate
  neighbor 2001:db8:1:ba:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:cc::1 activate
  neighbor 2001:db8:1:cc::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:cd::1 activate
  neighbor 2001:db8:1:cd::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:ce::1 activate
  neighbor 2001:db8:1:ce::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1028::/48 locator MAIN behavior uN
   sid fc00:0:1028:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:e000::/48 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:14::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:47::
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet8 nexthop 2001:db8:1:79::
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet12 nexthop 2001:db8:1:a0::
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet16 nexthop 2001:db8:1:ba::
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet20 nexthop 2001:db8:1:cc::1
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet24 nexthop 2001:db8:1:cd::1
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet28 nexthop 2001:db8:1:ce::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1028::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1028::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
