hostname sw035
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.35
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1023::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65035
 bgp router-id 1.1.0.35
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:31:: remote-as 65007
 neighbor 2001:db8:1:31:: capability extended-nexthop
 neighbor 2001:db8:1:53:: remote-as 65013
 neighbor 2001:db8:1:53:: capability extended-nexthop
 neighbor 2001:db8:1:72:: remote-as 65018
 neighbor 2001:db8:1:72:: capability extended-nexthop
 neighbor 2001:db8:1:90:: remote-as 65023
 neighbor 2001:db8:1:90:: capability extended-nexthop
 neighbor 2001:db8:1:ba::1 remote-as 65040
 neighbor 2001:db8:1:ba::1 capability extended-nexthop
 neighbor 2001:db8:1:bb::1 remote-as 65045
 neighbor 2001:db8:1:bb::1 capability extended-nexthop
 neighbor 2001:db8:1:bc::1 remote-as 65057
 neighbor 2001:db8:1:bc::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1023::/48
  network fc00:0:1023::1/128
  neighbor 2001:db8:1:31:: activate
  neighbor 2001:db8:1:31:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:53:: activate
  neighbor 2001:db8:1:53:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:72:: activate
  neighbor 2001:db8:1:72:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:90:: activate
  neighbor 2001:db8:1:90:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:ba::1 activate
  neighbor 2001:db8:1:ba::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:bb::1 activate
  neighbor 2001:db8:1:bb::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:bc::1 activate
  neighbor 2001:db8:1:bc::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1023::/48 locator MAIN behavior uN
   sid fc00:0:1023:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:e000::/48 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:31::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet1 nexthop 2001:db8:1:53::
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet2 nexthop 2001:db8:1:72::
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet3 nexthop 2001:db8:1:90::
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:ba::1
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet5 nexthop 2001:db8:1:bb::1
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet6 nexthop 2001:db8:1:bc::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1023::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1023::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
