#!/usr/bin/env python3
"""
Polarfly XRd (IOS-XR) containerlab topology generator.

Reuses the Erdős–Rényi polarity graph and addressing from polarfly_clab.py,
and emits a containerlab YAML + per-switch IOS-XR startup configs for
Cisco XRd control-plane containers.

IPv6 addressing, ASNs, SRv6 locators, and static uA SIDs are identical
to the SONiC variant so the two fabrics are wire-compatible at the
IP/SRv6 level.

Usage:
  python3 polarfly_xrd.py              # q=7 (default), writes ../q7/xrd/
  python3 polarfly_xrd.py --q 7        # explicit
  python3 polarfly_xrd.py --q 13       # q=13 (183 switches)
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Dict, List

# Import shared topology logic from the SONiC generator.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from polarfly_clab import (          # noqa: E402
    is_prime,
    projective_points,
    polarity_edges,
    verify,
    build_wiring,
)


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def _xrd_name(idx0: int, width: int = 3) -> str:
    """XRd node name from 0-based index: xrd001 .. xrdNNN."""
    return f"xrd{idx0 + 1:0{width}d}"


def _host_name(idx0: int, width: int = 3) -> str:
    return f"h{idx0 + 1:0{width}d}"


def _gi_full(port_idx: int) -> str:
    """Full IOS-XR interface name: GigabitEthernet0/0/0/<N>."""
    return f"GigabitEthernet0/0/0/{port_idx}"


def _gi_clab(port_idx: int) -> str:
    """Containerlab endpoint label for XRd GigE interfaces."""
    return f"Gi0-0-0-{port_idx}"


# ---------------------------------------------------------------------------
# Containerlab YAML emitter
# ---------------------------------------------------------------------------

def emit_xrd_yaml(wiring: Dict, q: int, out_path: str) -> None:
    n = wiring["n"]
    switches = wiring["switches"]
    edges = wiring["edges"]
    absolute = wiring["absolute"]
    width = wiring["width"]

    L: List[str] = []
    a = L.append

    a(f"# Polarfly q={q} XRd containerlab topology")
    a("# Generated by topogen2/polarfly_xrd.py")
    a(f"# Switches:        {n}")
    a(f"# Fabric links:    {len(edges)}")
    a(f"# Host links:      {n}")
    a(f"# Absolute points: {len(absolute)}  ({sorted(absolute)})")
    a("")
    a(f"name: xrd-polarfly-q{q}")
    a('prefix: ""')
    a("")
    a("mgmt:")
    a("  network: mgt_net_xrd")
    a("  ipv4-subnet: 172.20.0.0/23")
    a("")
    a("topology:")
    a("  kinds:")
    a("    cisco_xrd:")
    a("      image: ios-xr/xrd-control-plane:25.4.1")
    a("    linux:")
    a("      image: iejalapeno/alpine-srv6:1.0")
    a("")
    a("  nodes:")

    # XRd switch nodes
    for s in switches:
        name = _xrd_name(s["idx"], width)
        ip = f"172.20.0.{11 + s['idx']}"
        a(f"    {name}:")
        a(f"      kind: cisco_xrd")
        a(f"      mgmt-ipv4: {ip}")
        a(f"      startup-config: xrd-config/{name}.cfg")
    a("")

    # Alpine host nodes
    for s in switches:
        name = _host_name(s["idx"], width)
        ip = f"172.20.1.{11 + s['idx']}"
        a(f"    {name}:")
        a(f"      kind: linux")
        a(f"      mgmt-ipv4: {ip}")
        a(f"      exec:")
        a(f'        - "ip -6 addr add {s["host_host_addr"]}/64 dev eth1 nodad"')
    a("")

    a("  links:")
    a("    # ---- fabric links (polarity adjacencies) ----")

    for e_idx, (u, v) in enumerate(edges):
        u_fp = next(p for p in switches[u]["fabric"] if p["edge_idx"] == e_idx)
        v_fp = next(p for p in switches[v]["fabric"] if p["edge_idx"] == e_idx)
        u_name = _xrd_name(u, width)
        v_name = _xrd_name(v, width)
        u_gi = _gi_clab(u_fp["local_idx"])
        v_gi = _gi_clab(v_fp["local_idx"])
        a(f'    - endpoints: ["{u_name}:{u_gi}", "{v_name}:{v_gi}"]')

    a("    # ---- host links (one alpine-srv6 per switch) ----")
    host_gi = _gi_clab(q + 1)
    for s in switches:
        sw = _xrd_name(s["idx"], width)
        h = _host_name(s["idx"], width)
        a(f'    - endpoints: ["{sw}:{host_gi}", "{h}:eth1"]')
    a("")

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(L))


# ---------------------------------------------------------------------------
# IOS-XR config emitter
# ---------------------------------------------------------------------------

def build_xrd_cfg(s: Dict, switches: List[Dict], q: int) -> str:
    """Build an IOS-XR startup config for one switch."""
    fabric = s["fabric"]
    width = max(3, len(str(len(switches))))

    L: List[str] = []
    p = L.append

    name = _xrd_name(s["idx"], width)

    # --- hostname / users ---
    p(f"hostname {name}")
    p("username cisco")
    p(" group root-lr")
    p(" group cisco-support")
    p(" secret 10 $6$GXFSDMYr1txD....$09ETAo1VMaFVXEu9HMDuV9y8fpXbZIHhgWe8nqvxotAaOOaTCxsC8QBzp3g1aVHFZUOtPuLFeLOaL.XsIpQHw.")
    p("!")

    # --- CDP / gRPC ---
    p("cdp")
    p("grpc")
    p(" port 57400")
    p(" no-tls")
    p(" address-family ipv4")
    p(" service-layer")
    p(" !")
    p("!")

    # --- Telemetry ---
    p("telemetry model-driven")
    p(" destination-group jalapeno")
    p("  address-family ipv4 198.18.133.102 port 32400")
    p("   encoding self-describing-gpb")
    p("   protocol grpc no-tls")
    p("  !")
    p(" !")
    p(" sensor-group cisco_models")
    p(" !")
    p(" sensor-group openconfig_interfaces")
    p("  sensor-path openconfig-interfaces:interfaces/interface")
    p(" !")
    p(" subscription base_metrics")
    p("  sensor-group-id cisco_models sample-interval 10000")
    p("  sensor-group-id openconfig_interfaces sample-interval 10000")
    p("  destination-id jalapeno")
    p("  source-interface MgmtEth0/RP0/CPU0/0")
    p(" !")
    p("!")

    # --- VRF ---
    p("vrf Vrf-tenant")
    p(" address-family ipv6 unicast")
    p(" !")
    p("!")

    # --- Loopback0 ---
    p("interface Loopback0")
    p(f" ipv6 address {s['loopback_v6']}/128")
    p("!")

    # --- Management ---
    p("interface MgmtEth0/RP0/CPU0/0")
    p(" description mgt")
    p(" no shutdown")
    p("!")

    # --- Fabric interfaces ---
    for fp in fabric:
        peer_name = _xrd_name(switches[fp["peer_sw"]]["idx"], width)
        p(f"interface {_gi_full(fp['local_idx'])}")
        p(f" description to {peer_name}")
        p(f" ipv6 address {fp['my_addr']}/127")
        p(" no shutdown")
        p("!")

    # --- Host interface (in VRF) ---
    h_name = _host_name(s["idx"], width)
    p(f"interface {_gi_full(q + 1)}")
    p(f" vrf Vrf-tenant")
    p(f" description to {h_name}")
    p(f" ipv6 address {s['host_sw_addr']}/64")
    p(" no shutdown")
    p("!")

    # --- Route policies ---
    p("route-policy drop")
    p("  drop")
    p("end-policy")
    p("!")
    p("route-policy pass")
    p("  pass")
    p("end-policy")
    p("!")

    # --- Static route for telemetry / BMP reachability ---
    p("router static")
    p(" address-family ipv4 unicast")
    p("  198.18.133.0/24 MgmtEth0/RP0/CPU0/0 172.20.0.1")
    p(" !")
    p("!")

    # --- BGP ---
    p(f"router bgp {s['asn']}")
    p(f" bgp router-id {s['loopback_v4']}")
    p(" address-family ipv6 unicast")
    p(f"  network {s['locator_prefix']}")
    p(f"  network {s['loopback_v6']}/128")
    p(" !")
    for fp in fabric:
        peer = switches[fp["peer_sw"]]
        p(f" neighbor {fp['peer_addr']}")
        p(f"  remote-as {peer['asn']}")
        p(f"  address-family ipv6 unicast")
        p(f"   route-policy pass in")
        p(f"   route-policy pass out")
        p(f"  !")
        p(f" !")
    # VRF with SRv6 uDT6 binding
    p(" vrf Vrf-tenant")
    p("  rd auto")
    p("  address-family ipv6 unicast")
    p("   segment-routing srv6")
    p("    locator MAIN")
    p("    alloc mode per-vrf")
    p("   !")
    p("  !")
    p(" !")
    p("!")

    # --- BMP ---
    p("bmp server 1")
    p(" host 198.18.133.102 port 30511")
    p(" description jalapeno GoBMP")
    p(" update-source MgmtEth0/RP0/CPU0/0")
    p(" flapping-delay 60")
    p(" initial-delay 5")
    p(" stats-reporting-period 60")
    p(" initial-refresh delay 25 spread 2")
    p("!")
    p("bmp server 2")
    p(" host 198.18.133.102 port 30512")
    p(" description GoBMP NATS")
    p(" update-source MgmtEth0/RP0/CPU0/0")
    p(" flapping-delay 60")
    p(" initial-delay 5")
    p(" stats-reporting-period 60")
    p(" initial-refresh delay 25 spread 2")
    p("!")

    # --- Segment Routing SRv6 ---
    p("segment-routing")
    p(" srv6")
    p("  encapsulation")
    p(f"   source-address {s['loopback_v6']}")
    p("  !")
    p("  locators")
    p("   locator MAIN")
    p("    micro-segment behavior unode psp-usd")
    p(f"    prefix {s['locator_prefix']}")
    p("   !")
    p("  !")
    # Static uA SIDs (same fc00:0:f<idx>::/48 scheme as SONiC)
    if fabric:
        p("  static")
        p("   endpoint")
        for fp in fabric:
            ua_sid = f"fc00:0:f{fp['local_idx']:03x}::/48"
            p(f"    sid {ua_sid} behavior end-ua-psp-usd")
            p(f"     allocation-context nexthop {_gi_full(fp['local_idx'])}")
            p("    !")
        p("  !")
    p(" !")
    p("!")

    # --- LLDP / SSH ---
    p("lldp")
    p("!")
    p("ssh server rate-limit 600")
    p("ssh server session-limit 100")
    p("ssh server v2")
    p("ssh server vrf default")
    p("ssh server netconf vrf default")
    p("end")

    return "\n".join(L)


def emit_xrd_configs(wiring: Dict, q: int, out_dir: str) -> int:
    """Write per-switch .cfg files into out_dir/. Returns count."""
    switches = wiring["switches"]
    width = wiring["width"]
    os.makedirs(out_dir, exist_ok=True)

    for s in switches:
        name = _xrd_name(s["idx"], width)
        cfg = build_xrd_cfg(s, switches, q)
        with open(os.path.join(out_dir, f"{name}.cfg"), "w") as fh:
            fh.write(cfg)
            fh.write("\n")

    return len(switches)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Polarfly XRd (IOS-XR) containerlab topology generator"
    )
    ap.add_argument("--q", type=int, default=7, help="prime order (default: 7)")

    here = os.path.dirname(os.path.abspath(__file__))
    default_topo_dir = os.path.normpath(os.path.join(here, "..", "q{q}", "xrd"))

    ap.add_argument(
        "--topo-dir",
        default=default_topo_dir,
        help="output directory (default: ../q{q}/xrd/); '{q}' is substituted",
    )
    args = ap.parse_args()

    q = args.q
    if not is_prime(q):
        print(f"error: q={q} is not prime", file=sys.stderr)
        return 2

    topo_dir = args.topo_dir.replace("{q}", str(q))

    # Build graph
    points = projective_points(q)
    edges, absolute = polarity_edges(points, q)
    verify(points, edges, absolute, q)

    # Build wiring (shared addressing with SONiC)
    wiring = build_wiring(points, edges, absolute, q)

    os.makedirs(topo_dir, exist_ok=True)

    yaml_path = os.path.join(topo_dir, f"xrd-polarfly-q{q}.clab.yaml")
    cfg_dir = os.path.join(topo_dir, "xrd-config")

    emit_xrd_yaml(wiring, q, yaml_path)
    cfg_count = emit_xrd_configs(wiring, q, cfg_dir)

    print(f"q                = {q}")
    print(f"switches         = {len(points)}")
    print(f"fabric radix     = {q + 1}")
    print(f"absolute points  = {len(absolute)}")
    print(f"fabric links     = {len(edges)}")
    print(f"host links       = {len(points)}")
    print(f"total links      = {len(edges) + len(points)}")
    print(f"clab YAML        = {yaml_path}")
    print(f"configs written  = {cfg_count} switches in {cfg_dir}/")

    return 0


if __name__ == "__main__":
    sys.exit(main())
