#!/usr/bin/env python3
"""
Polarfly containerlab topology generator.

Builds the Erdős–Rényi polarity graph of the projective plane PG(2, q)
for prime q, and emits a containerlab YAML wiring `docker-sonic-vs:latest`
switches according to that graph, with one `iejalapeno/alpine-srv6:1.0`
host attached to each switch.

For q = 13 (default):
  - Nodes (switches):     q^2 + q + 1                  = 183
  - Fabric radix:         q + 1                        = 14
  - Absolute points:      q + 1                        = 14
  - Fabric links:         (n*(q+1) - absolute_count)/2 = 1274
  - Host links (1/sw):                                 = 183
  - Total containers:                                  = 366
  - Total links:                                       = 1457

Polarity (self-duality): point P=(a,b,c) is adjacent to Q=(d,e,f) iff
  a*d + b*e + c*f ≡ 0 (mod q).
A point is "absolute" iff a^2 + b^2 + c^2 ≡ 0 (mod q); these contribute
a self-loop in the abstract graph, which we drop physically (one less
fabric port used on those switches).

Usage:
  python3 polarfly_clab.py            # q=13, writes ../sonic-polarfly.clab.yaml
  python3 polarfly_clab.py --q 5      # smaller test fabric
  python3 polarfly_clab.py --q 13 --out /path/to/topo.yaml

Stdlib only (no galois/sympy needed for small primes).
"""

from __future__ import annotations

import argparse
import os
import sys
from itertools import product
from typing import List, Tuple


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n % 2 == 0:
        return n == 2
    i = 3
    while i * i <= n:
        if n % i == 0:
            return False
        i += 2
    return True


def projective_points(q: int) -> List[Tuple[int, int, int]]:
    """Canonical representatives of points in PG(2, q): leading nonzero coord = 1."""
    pts: List[Tuple[int, int, int]] = []
    for a, b, c in product(range(q), repeat=3):
        if (a, b, c) == (0, 0, 0):
            continue
        # Normalize: scale so first nonzero coordinate is 1.
        if a != 0:
            inv = pow(a, -1, q)
            rep = (1, (b * inv) % q, (c * inv) % q)
        elif b != 0:
            inv = pow(b, -1, q)
            rep = (0, 1, (c * inv) % q)
        else:
            rep = (0, 0, 1)
        if rep == (a, b, c):
            pts.append(rep)
    expected = q * q + q + 1
    assert len(pts) == expected, f"got {len(pts)} points, expected {expected}"
    return pts


def polarity_edges(points: List[Tuple[int, int, int]], q: int):
    """Return (edges, absolute_indices). Edges are i<j adjacency pairs."""
    edges: List[Tuple[int, int]] = []
    absolute: List[int] = []
    n = len(points)
    for i in range(n):
        a, b, c = points[i]
        if (a * a + b * b + c * c) % q == 0:
            absolute.append(i)
        for j in range(i + 1, n):
            d, e, f = points[j]
            if (a * d + b * e + c * f) % q == 0:
                edges.append((i, j))
    return edges, absolute


def verify(points, edges, absolute, q: int) -> None:
    n = len(points)
    deg = [0] * n
    for i, j in edges:
        deg[i] += 1
        deg[j] += 1
    abs_set = set(absolute)
    for v in range(n):
        expected = q if v in abs_set else q + 1
        assert deg[v] == expected, (
            f"vertex {v} has degree {deg[v]}, expected {expected}"
        )
    expected_edges = (n * (q + 1) - len(absolute)) // 2
    assert len(edges) == expected_edges, (
        f"got {len(edges)} edges, expected {expected_edges}"
    )
    assert len(absolute) == q + 1, (
        f"got {len(absolute)} absolute points, expected {q + 1}"
    )


def mgmt_ip(network_24_third_octet: int, host: int) -> str:
    return f"172.100.{network_24_third_octet}.{host}"


def emit_yaml(points, edges, absolute, q: int, out_path: str) -> None:
    n = len(points)
    width = max(3, len(str(n)))

    def sw(i: int) -> str:
        return f"sw{i + 1:0{width}d}"

    def host(i: int) -> str:
        return f"h{i + 1:0{width}d}"

    # Per-switch fabric port counter. sonic-vs uses Ethernet0, Ethernet4, ...
    next_fab_port = [0] * n
    abs_set = set(absolute)

    def alloc_fab(v: int) -> str:
        idx = next_fab_port[v]
        next_fab_port[v] += 1
        # Hard cap: non-absolute -> q+1 fabric ports, absolute -> q
        cap = q if v in abs_set else q + 1
        assert idx < cap, f"port overflow on {sw(v)}"
        return f"Ethernet{idx * 4}"

    # Reserve a fixed host port well past any fabric port: 4*(q+1) = Ethernet{4q+4}
    host_port = f"Ethernet{4 * (q + 1)}"

    lines: List[str] = []
    lines.append(f"# Polarfly q={q} containerlab topology")
    lines.append(f"# Generated by topogen2/polarfly_clab.py")
    lines.append(f"# Switches:        {n}")
    lines.append(f"# Fabric links:    {len(edges)}")
    lines.append(f"# Host links:      {n}")
    lines.append(f"# Absolute points: {len(absolute)}  ({sorted(absolute)})")
    lines.append("")
    lines.append("name: sonic-polarfly")
    lines.append('prefix: ""')
    lines.append("")
    lines.append("mgmt:")
    lines.append("  network: mgmt-net")
    lines.append("  ipv4-subnet: 172.100.0.0/23")
    lines.append("")
    lines.append("topology:")
    lines.append("  kinds:")
    lines.append("    sonic-vs:")
    lines.append("      image: docker-sonic-vs:latest")
    lines.append("    linux:")
    lines.append("      image: iejalapeno/alpine-srv6:1.0")
    lines.append("")
    lines.append("  nodes:")
    # Switches: 172.100.0.11 .. (skip .0/.1/.2/.10 for gw/reservations)
    for i in range(n):
        ip = f"172.100.0.{11 + i}"
        # /23 spans 172.100.0.0 - 172.100.1.255; .11 + 182 = .193 (still in .0/24)
        lines.append(f"    {sw(i)}: {{ kind: sonic-vs, mgmt-ipv4: {ip} }}")
    lines.append("")
    # Hosts: 172.100.1.11 ..
    for i in range(n):
        ip = f"172.100.1.{11 + i}"
        lines.append(f"    {host(i)}: {{ kind: linux, mgmt-ipv4: {ip} }}")
    lines.append("")
    lines.append("  links:")
    lines.append("    # ---- fabric links (polarity adjacencies) ----")
    for u, v in edges:
        pu = alloc_fab(u)
        pv = alloc_fab(v)
        lines.append(f'    - endpoints: ["{sw(u)}:{pu}", "{sw(v)}:{pv}"]')
    lines.append("    # ---- host links (one alpine-srv6 per switch) ----")
    for i in range(n):
        lines.append(
            f'    - endpoints: ["{sw(i)}:{host_port}", "{host(i)}:eth1"]'
        )
    lines.append("")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))


def emit_adjlist(points, edges, q: int, out_path: str) -> None:
    n = len(points)
    width = max(3, len(str(n)))
    with open(out_path, "w") as fh:
        fh.write(f"# Polarfly q={q} adjacency (sidecar)\n")
        fh.write(f"# {n} vertices, {len(edges)} edges\n")
        fh.write("# index  point(a:b:c)\n")
        for i, p in enumerate(points):
            fh.write(f"V {i + 1:0{width}d}  {p[0]}:{p[1]}:{p[2]}\n")
        fh.write("# i  j  (1-indexed switch IDs)\n")
        for u, v in edges:
            fh.write(f"E {u + 1:0{width}d} {v + 1:0{width}d}\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--q", type=int, default=13, help="prime order (default: 13)")
    here = os.path.dirname(os.path.abspath(__file__))
    default_out = os.path.normpath(os.path.join(here, "..", "sonic-polarfly.clab.yaml"))
    default_adj = os.path.normpath(os.path.join(here, "..", "polarfly-q{q}.adj.txt"))
    ap.add_argument("--out", default=default_out, help="output containerlab YAML path")
    ap.add_argument(
        "--adj",
        default=default_adj,
        help="adjacency sidecar path ('{q}' is substituted)",
    )
    args = ap.parse_args()

    if not is_prime(args.q):
        # Prime power would also work mathematically, but requires GF(p^k)
        # arithmetic which is out of scope for this stdlib generator.
        print(
            f"error: q={args.q} is not prime; only prime q is supported here.",
            file=sys.stderr,
        )
        return 2

    points = projective_points(args.q)
    edges, absolute = polarity_edges(points, args.q)
    verify(points, edges, absolute, args.q)

    adj_path = args.adj.replace("{q}", str(args.q))
    emit_yaml(points, edges, absolute, args.q, args.out)
    emit_adjlist(points, edges, args.q, adj_path)

    print(f"q                = {args.q}")
    print(f"switches         = {len(points)}")
    print(f"fabric radix     = {args.q + 1}")
    print(f"absolute points  = {len(absolute)}")
    print(f"fabric links     = {len(edges)}")
    print(f"host links       = {len(points)}")
    print(f"total links      = {len(edges) + len(points)}")
    print(f"yaml             = {args.out}")
    print(f"adj sidecar      = {adj_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
