hostname sw051
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.51
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1033::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65051
 bgp router-id 1.1.0.51
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:7:: remote-as 65001
 neighbor 2001:db8:1:7:: capability extended-nexthop
 neighbor 2001:db8:1:63:: remote-as 65016
 neighbor 2001:db8:1:63:: capability extended-nexthop
 neighbor 2001:db8:1:6f:: remote-as 65017
 neighbor 2001:db8:1:6f:: capability extended-nexthop
 neighbor 2001:db8:1:75:: remote-as 65018
 neighbor 2001:db8:1:75:: capability extended-nexthop
 neighbor 2001:db8:1:7b:: remote-as 65019
 neighbor 2001:db8:1:7b:: capability extended-nexthop
 neighbor 2001:db8:1:80:: remote-as 65020
 neighbor 2001:db8:1:80:: capability extended-nexthop
 neighbor 2001:db8:1:85:: remote-as 65021
 neighbor 2001:db8:1:85:: capability extended-nexthop
 neighbor 2001:db8:1:8a:: remote-as 65022
 neighbor 2001:db8:1:8a:: capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1033::/48
  network fc00:0:1033::1/128
  neighbor 2001:db8:1:7:: activate
  neighbor 2001:db8:1:7:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:63:: activate
  neighbor 2001:db8:1:63:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:6f:: activate
  neighbor 2001:db8:1:6f:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:75:: activate
  neighbor 2001:db8:1:75:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:7b:: activate
  neighbor 2001:db8:1:7b:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:80:: activate
  neighbor 2001:db8:1:80:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:85:: activate
  neighbor 2001:db8:1:85:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:8a:: activate
  neighbor 2001:db8:1:8a:: route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1033::/48 locator MAIN behavior uN
   sid fc00:0:1033:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:e000::/48 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:7::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet1 nexthop 2001:db8:1:63::
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet2 nexthop 2001:db8:1:6f::
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet3 nexthop 2001:db8:1:75::
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:7b::
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet5 nexthop 2001:db8:1:80::
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet6 nexthop 2001:db8:1:85::
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet7 nexthop 2001:db8:1:8a::
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1033::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1033::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
