apiVersion: jalapeno.srv6/v1
kind: PathRequest
metadata:
  name: path-request
spec:
  defaultVrf:
    ipv6:
      routes:
        - name: example
          graph: ipv6_graph
          path_type: best-paths
          limit: 3
          source: igp_node/2_0_0_0000.0001.0000
          destination: igp_node/2_0_0_0000.0001.0029
          direction: outbound