hostname sw024
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.24
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1018::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65024
 bgp router-id 1.1.0.24
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:30:: remote-as 65007
 neighbor 2001:db8:1:30:: capability extended-nexthop
 neighbor 2001:db8:1:5e:: remote-as 65015
 neighbor 2001:db8:1:5e:: capability extended-nexthop
 neighbor 2001:db8:1:7c:: remote-as 65020
 neighbor 2001:db8:1:7c:: capability extended-nexthop
 neighbor 2001:db8:1:92::1 remote-as 65025
 neighbor 2001:db8:1:92::1 capability extended-nexthop
 neighbor 2001:db8:1:93::1 remote-as 65030
 neighbor 2001:db8:1:93::1 capability extended-nexthop
 neighbor 2001:db8:1:94::1 remote-as 65042
 neighbor 2001:db8:1:94::1 capability extended-nexthop
 neighbor 2001:db8:1:95::1 remote-as 65047
 neighbor 2001:db8:1:95::1 capability extended-nexthop
 neighbor 2001:db8:1:96::1 remote-as 65052
 neighbor 2001:db8:1:96::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1018::/48
  network fc00:0:1018::1/128
  neighbor 2001:db8:1:30:: activate
  neighbor 2001:db8:1:30:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:5e:: activate
  neighbor 2001:db8:1:5e:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:7c:: activate
  neighbor 2001:db8:1:7c:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:92::1 activate
  neighbor 2001:db8:1:92::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:93::1 activate
  neighbor 2001:db8:1:93::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:94::1 activate
  neighbor 2001:db8:1:94::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:95::1 activate
  neighbor 2001:db8:1:95::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:96::1 activate
  neighbor 2001:db8:1:96::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1018::/48 locator MAIN behavior uN
   sid fc00:0:1018:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:e000::/48 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:30::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet1 nexthop 2001:db8:1:5e::
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet2 nexthop 2001:db8:1:7c::
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet3 nexthop 2001:db8:1:92::1
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:93::1
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet5 nexthop 2001:db8:1:94::1
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet6 nexthop 2001:db8:1:95::1
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet7 nexthop 2001:db8:1:96::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1018::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1018::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
