hostname sw016
no service integrated-vtysh-config
!
route-map BGP-IPV6 permit 20
 set ipv6 next-hop prefer-global
exit
!
route-map RM_SET_SRC permit 10
 set src 1.1.0.16
exit
!
route-map RM_SET_SRC6 permit 10
 set src fc00:0:1010::1
exit
!
password zebra
enable password zebra
!
vrf Vrf-tenant
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf vrfdefault
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
router bgp 65016
 bgp router-id 1.1.0.16
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 no bgp network import-check
 neighbor 2001:db8:1:2:: remote-as 65001
 neighbor 2001:db8:1:2:: capability extended-nexthop
 neighbor 2001:db8:1:63::1 remote-as 65051
 neighbor 2001:db8:1:63::1 capability extended-nexthop
 neighbor 2001:db8:1:64::1 remote-as 65052
 neighbor 2001:db8:1:64::1 capability extended-nexthop
 neighbor 2001:db8:1:65::1 remote-as 65053
 neighbor 2001:db8:1:65::1 capability extended-nexthop
 neighbor 2001:db8:1:66::1 remote-as 65054
 neighbor 2001:db8:1:66::1 capability extended-nexthop
 neighbor 2001:db8:1:67::1 remote-as 65055
 neighbor 2001:db8:1:67::1 capability extended-nexthop
 neighbor 2001:db8:1:68::1 remote-as 65056
 neighbor 2001:db8:1:68::1 capability extended-nexthop
 neighbor 2001:db8:1:69::1 remote-as 65057
 neighbor 2001:db8:1:69::1 capability extended-nexthop
 !
 address-family ipv6 unicast
  network fc00:0:1010::/48
  network fc00:0:1010::1/128
  neighbor 2001:db8:1:2:: activate
  neighbor 2001:db8:1:2:: route-map BGP-IPV6 in
  neighbor 2001:db8:1:63::1 activate
  neighbor 2001:db8:1:63::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:64::1 activate
  neighbor 2001:db8:1:64::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:65::1 activate
  neighbor 2001:db8:1:65::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:66::1 activate
  neighbor 2001:db8:1:66::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:67::1 activate
  neighbor 2001:db8:1:67::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:68::1 activate
  neighbor 2001:db8:1:68::1 route-map BGP-IPV6 in
  neighbor 2001:db8:1:69::1 activate
  neighbor 2001:db8:1:69::1 route-map BGP-IPV6 in
  maximum-paths 64
 exit-address-family
exit
!
ip protocol bgp route-map RM_SET_SRC
!
ipv6 protocol bgp route-map RM_SET_SRC6
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 srv6
  static-sids
   sid fc00:0:1010::/48 locator MAIN behavior uN
   sid fc00:0:1010:e000::/64 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:e000::/48 locator MAIN behavior uDT6 vrf Vrf-tenant
   sid fc00:0:f000::/48 locator MAIN behavior uA interface Ethernet0 nexthop 2001:db8:1:2::
   sid fc00:0:f001::/48 locator MAIN behavior uA interface Ethernet1 nexthop 2001:db8:1:63::1
   sid fc00:0:f002::/48 locator MAIN behavior uA interface Ethernet2 nexthop 2001:db8:1:64::1
   sid fc00:0:f003::/48 locator MAIN behavior uA interface Ethernet3 nexthop 2001:db8:1:65::1
   sid fc00:0:f004::/48 locator MAIN behavior uA interface Ethernet4 nexthop 2001:db8:1:66::1
   sid fc00:0:f005::/48 locator MAIN behavior uA interface Ethernet5 nexthop 2001:db8:1:67::1
   sid fc00:0:f006::/48 locator MAIN behavior uA interface Ethernet6 nexthop 2001:db8:1:68::1
   sid fc00:0:f007::/48 locator MAIN behavior uA interface Ethernet7 nexthop 2001:db8:1:69::1
  exit
  !
 exit
 !
 srv6
  encapsulation
   source-address fc00:0:1010::1
  exit
  locators
   locator MAIN
    prefix fc00:0:1010::/48 block-len 32 node-len 16
    behavior usid
    format usid-f3216
   exit
   !
  exit
  !
  formats
   format usid-f3216
    local-id-block explicit start 57344 end 65535
   exit
   !
  exit
  !
 exit
 !
exit
!
end
